{
 "cells": [
  {
   "cell_type": "markdown",
   "source": [
    "###### Chatbot with Personality: just for fun, testing code\n",
    "\n",
    "\n"
   ],
   "metadata": {
    "collapsed": false
   },
   "id": "1ee98b4fdbdbd6d0"
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Looking in indexes: https://pypi.org/simple, https://aishwarya.mundalik:****@artifactory.softgarden.de/artifactory/api/pypi/python-local/simple\r\n",
      "\u001B[33mWARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x1121cd990>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /artifactory/api/pypi/python-local/simple/textblob/\u001B[0m\u001B[33m\r\n",
      "\u001B[0m\u001B[33mWARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x1121ce410>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /artifactory/api/pypi/python-local/simple/textblob/\u001B[0m\u001B[33m\r\n",
      "\u001B[0m\u001B[33mWARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x1121cebd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /artifactory/api/pypi/python-local/simple/textblob/\u001B[0m\u001B[33m\r\n",
      "\u001B[0m\u001B[33mWARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x1121cf610>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /artifactory/api/pypi/python-local/simple/textblob/\u001B[0m\u001B[33m\r\n",
      "\u001B[0m\u001B[33mWARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x1121cff90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /artifactory/api/pypi/python-local/simple/textblob/\u001B[0m\u001B[33m\r\n",
      "\u001B[0mCollecting textblob\r\n",
      "  Downloading textblob-0.19.0-py3-none-any.whl.metadata (4.4 kB)\r\n",
      "Requirement already satisfied: nltk in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (3.9.1)\r\n",
      "Requirement already satisfied: click in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (from nltk) (8.1.7)\r\n",
      "Requirement already satisfied: joblib in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (from nltk) (1.4.2)\r\n",
      "Requirement already satisfied: regex>=2021.8.3 in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (from nltk) (2024.11.6)\r\n",
      "Requirement already satisfied: tqdm in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (from nltk) (4.67.1)\r\n",
      "Downloading textblob-0.19.0-py3-none-any.whl (624 kB)\r\n",
      "\u001B[2K   \u001B[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001B[0m \u001B[32m624.3/624.3 kB\u001B[0m \u001B[31m10.1 MB/s\u001B[0m eta \u001B[36m0:00:00\u001B[0m\r\n",
      "\u001B[?25hInstalling collected packages: textblob\r\n",
      "Successfully installed textblob-0.19.0\r\n",
      "Looking in indexes: https://pypi.org/simple, https://aishwarya.mundalik:****@artifactory.softgarden.de/artifactory/api/pypi/python-local/simple\r\n",
      "\u001B[33mWARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10e754c10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /artifactory/api/pypi/python-local/simple/chatterbot/\u001B[0m\u001B[33m\r\n",
      "\u001B[0m\u001B[33mWARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10e755210>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /artifactory/api/pypi/python-local/simple/chatterbot/\u001B[0m\u001B[33m\r\n",
      "\u001B[0m\u001B[33mWARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10e755b10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /artifactory/api/pypi/python-local/simple/chatterbot/\u001B[0m\u001B[33m\r\n",
      "\u001B[0m\u001B[33mWARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10e756350>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /artifactory/api/pypi/python-local/simple/chatterbot/\u001B[0m\u001B[33m\r\n",
      "\u001B[0m\u001B[33mWARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10e756b10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /artifactory/api/pypi/python-local/simple/chatterbot/\u001B[0m\u001B[33m\r\n",
      "\u001B[0mCollecting chatterbot\r\n",
      "  Downloading chatterbot-1.2.3-py3-none-any.whl.metadata (8.5 kB)\r\n",
      "\u001B[33mWARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10e781590>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /artifactory/api/pypi/python-local/simple/mathparse/\u001B[0m\u001B[33m\r\n",
      "\u001B[0m\u001B[33mWARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10e781a50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /artifactory/api/pypi/python-local/simple/mathparse/\u001B[0m\u001B[33m\r\n",
      "\u001B[0m\u001B[33mWARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10e78d050>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /artifactory/api/pypi/python-local/simple/mathparse/\u001B[0m\u001B[33m\r\n",
      "\u001B[0m\u001B[33mWARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10e78d6d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /artifactory/api/pypi/python-local/simple/mathparse/\u001B[0m\u001B[33m\r\n",
      "\u001B[0m\u001B[33mWARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10c62ac10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /artifactory/api/pypi/python-local/simple/mathparse/\u001B[0m\u001B[33m\r\n",
      "\u001B[0mCollecting mathparse<0.2,>=0.1 (from chatterbot)\r\n",
      "  Downloading mathparse-0.1.2-py3-none-any.whl.metadata (776 bytes)\r\n",
      "Requirement already satisfied: python-dateutil<2.10,>=2.9 in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (from chatterbot) (2.9.0.post0)\r\n",
      "Requirement already satisfied: sqlalchemy<2.1,>=2.0 in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (from chatterbot) (2.0.36)\r\n",
      "\u001B[33mWARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10e90e390>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /artifactory/api/pypi/python-local/simple/spacy/\u001B[0m\u001B[33m\r\n",
      "\u001B[0m\u001B[33mWARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10e90f190>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /artifactory/api/pypi/python-local/simple/spacy/\u001B[0m\u001B[33m\r\n",
      "\u001B[0m\u001B[33mWARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10e90fb50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /artifactory/api/pypi/python-local/simple/spacy/\u001B[0m\u001B[33m\r\n",
      "\u001B[0m\u001B[33mWARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10e92c550>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /artifactory/api/pypi/python-local/simple/spacy/\u001B[0m\u001B[33m\r\n",
      "\u001B[0m\u001B[33mWARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10e92ced0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /artifactory/api/pypi/python-local/simple/spacy/\u001B[0m\u001B[33m\r\n",
      "\u001B[0mCollecting spacy<3.9,>=3.8 (from chatterbot)\r\n",
      "  Downloading spacy-3.8.4-cp311-cp311-macosx_10_9_x86_64.whl.metadata (27 kB)\r\n",
      "Requirement already satisfied: tqdm in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (from chatterbot) (4.67.1)\r\n",
      "Requirement already satisfied: six>=1.5 in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (from python-dateutil<2.10,>=2.9->chatterbot) (1.16.0)\r\n",
      "Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (from spacy<3.9,>=3.8->chatterbot) (3.0.12)\r\n",
      "Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (from spacy<3.9,>=3.8->chatterbot) (1.0.5)\r\n",
      "Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (from spacy<3.9,>=3.8->chatterbot) (1.0.11)\r\n",
      "Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (from spacy<3.9,>=3.8->chatterbot) (2.0.10)\r\n",
      "Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (from spacy<3.9,>=3.8->chatterbot) (3.0.9)\r\n",
      "\u001B[33mWARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10ecf3450>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /artifactory/api/pypi/python-local/simple/thinc/\u001B[0m\u001B[33m\r\n",
      "\u001B[0m\u001B[33mWARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10ecf2a90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /artifactory/api/pypi/python-local/simple/thinc/\u001B[0m\u001B[33m\r\n",
      "\u001B[0m\u001B[33mWARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10ecf4a90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /artifactory/api/pypi/python-local/simple/thinc/\u001B[0m\u001B[33m\r\n",
      "\u001B[0m\u001B[33mWARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10ecf5450>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /artifactory/api/pypi/python-local/simple/thinc/\u001B[0m\u001B[33m\r\n",
      "\u001B[0m\u001B[33mWARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10ecf5f50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /artifactory/api/pypi/python-local/simple/thinc/\u001B[0m\u001B[33m\r\n",
      "\u001B[0mCollecting thinc<8.4.0,>=8.3.4 (from spacy<3.9,>=3.8->chatterbot)\r\n",
      "  Downloading thinc-8.3.4-cp311-cp311-macosx_10_9_x86_64.whl.metadata (15 kB)\r\n",
      "Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (from spacy<3.9,>=3.8->chatterbot) (1.1.3)\r\n",
      "Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (from spacy<3.9,>=3.8->chatterbot) (2.4.8)\r\n",
      "Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (from spacy<3.9,>=3.8->chatterbot) (2.0.10)\r\n",
      "Requirement already satisfied: weasel<0.5.0,>=0.1.0 in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (from spacy<3.9,>=3.8->chatterbot) (0.4.1)\r\n",
      "Requirement already satisfied: typer<1.0.0,>=0.3.0 in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (from spacy<3.9,>=3.8->chatterbot) (0.15.1)\r\n",
      "Requirement already satisfied: numpy>=1.19.0 in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (from spacy<3.9,>=3.8->chatterbot) (1.26.4)\r\n",
      "Requirement already satisfied: requests<3.0.0,>=2.13.0 in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (from spacy<3.9,>=3.8->chatterbot) (2.32.3)\r\n",
      "Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (from spacy<3.9,>=3.8->chatterbot) (1.10.19)\r\n",
      "Requirement already satisfied: jinja2 in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (from spacy<3.9,>=3.8->chatterbot) (3.1.4)\r\n",
      "Requirement already satisfied: setuptools in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (from spacy<3.9,>=3.8->chatterbot) (75.1.0)\r\n",
      "Requirement already satisfied: packaging>=20.0 in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (from spacy<3.9,>=3.8->chatterbot) (24.1)\r\n",
      "Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (from spacy<3.9,>=3.8->chatterbot) (3.5.0)\r\n",
      "Requirement already satisfied: typing-extensions>=4.6.0 in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (from sqlalchemy<2.1,>=2.0->chatterbot) (4.12.2)\r\n",
      "Requirement already satisfied: greenlet!=0.4.17 in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (from sqlalchemy<2.1,>=2.0->chatterbot) (3.1.1)\r\n",
      "Requirement already satisfied: language-data>=1.2 in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (from langcodes<4.0.0,>=3.2.0->spacy<3.9,>=3.8->chatterbot) (1.3.0)\r\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.9,>=3.8->chatterbot) (3.3.2)\r\n",
      "Requirement already satisfied: idna<4,>=2.5 in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.9,>=3.8->chatterbot) (3.10)\r\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.9,>=3.8->chatterbot) (1.26.20)\r\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.9,>=3.8->chatterbot) (2024.8.30)\r\n",
      "\u001B[33mWARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10e985990>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /artifactory/api/pypi/python-local/simple/blis/\u001B[0m\u001B[33m\r\n",
      "\u001B[0m\u001B[33mWARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10e9866d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /artifactory/api/pypi/python-local/simple/blis/\u001B[0m\u001B[33m\r\n",
      "\u001B[0m\u001B[33mWARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10e987350>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /artifactory/api/pypi/python-local/simple/blis/\u001B[0m\u001B[33m\r\n",
      "\u001B[0m\u001B[33mWARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10e987b90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /artifactory/api/pypi/python-local/simple/blis/\u001B[0m\u001B[33m\r\n",
      "\u001B[0m\u001B[33mWARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10ed24710>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /artifactory/api/pypi/python-local/simple/blis/\u001B[0m\u001B[33m\r\n",
      "\u001B[0mCollecting blis<1.3.0,>=1.2.0 (from thinc<8.4.0,>=8.3.4->spacy<3.9,>=3.8->chatterbot)\r\n",
      "  Downloading blis-1.2.0-cp311-cp311-macosx_10_9_x86_64.whl.metadata (7.7 kB)\r\n",
      "Requirement already satisfied: confection<1.0.0,>=0.0.1 in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (from thinc<8.4.0,>=8.3.4->spacy<3.9,>=3.8->chatterbot) (0.1.5)\r\n",
      "Requirement already satisfied: click>=8.0.0 in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (from typer<1.0.0,>=0.3.0->spacy<3.9,>=3.8->chatterbot) (8.1.7)\r\n",
      "Requirement already satisfied: shellingham>=1.3.0 in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (from typer<1.0.0,>=0.3.0->spacy<3.9,>=3.8->chatterbot) (1.5.4)\r\n",
      "Requirement already satisfied: rich>=10.11.0 in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (from typer<1.0.0,>=0.3.0->spacy<3.9,>=3.8->chatterbot) (13.9.4)\r\n",
      "Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (from weasel<0.5.0,>=0.1.0->spacy<3.9,>=3.8->chatterbot) (0.20.0)\r\n",
      "Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (from weasel<0.5.0,>=0.1.0->spacy<3.9,>=3.8->chatterbot) (7.0.5)\r\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (from jinja2->spacy<3.9,>=3.8->chatterbot) (2.1.3)\r\n",
      "Requirement already satisfied: marisa-trie>=1.1.0 in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy<3.9,>=3.8->chatterbot) (1.2.1)\r\n",
      "Requirement already satisfied: markdown-it-py>=2.2.0 in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.9,>=3.8->chatterbot) (3.0.0)\r\n",
      "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.9,>=3.8->chatterbot) (2.15.1)\r\n",
      "Requirement already satisfied: wrapt in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy<3.9,>=3.8->chatterbot) (1.17.0)\r\n",
      "Requirement already satisfied: mdurl~=0.1 in /Users/aishwaryamundalik/anaconda3/envs/DI-dwh-import/lib/python3.11/site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.9,>=3.8->chatterbot) (0.1.2)\r\n",
      "Downloading chatterbot-1.2.3-py3-none-any.whl (72 kB)\r\n",
      "Downloading mathparse-0.1.2-py3-none-any.whl (7.2 kB)\r\n",
      "Downloading spacy-3.8.4-cp311-cp311-macosx_10_9_x86_64.whl (6.6 MB)\r\n",
      "\u001B[2K   \u001B[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001B[0m \u001B[32m6.6/6.6 MB\u001B[0m \u001B[31m12.9 MB/s\u001B[0m eta \u001B[36m0:00:00\u001B[0m \u001B[36m0:00:01\u001B[0mm\r\n",
      "\u001B[?25hDownloading thinc-8.3.4-cp311-cp311-macosx_10_9_x86_64.whl (839 kB)\r\n",
      "\u001B[2K   \u001B[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001B[0m \u001B[32m839.3/839.3 kB\u001B[0m \u001B[31m11.5 MB/s\u001B[0m eta \u001B[36m0:00:00\u001B[0m\r\n",
      "\u001B[?25hDownloading blis-1.2.0-cp311-cp311-macosx_10_9_x86_64.whl (7.0 MB)\r\n",
      "\u001B[2K   \u001B[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001B[0m \u001B[32m7.0/7.0 MB\u001B[0m \u001B[31m12.9 MB/s\u001B[0m eta \u001B[36m0:00:00\u001B[0ma \u001B[36m0:00:01\u001B[0m\r\n",
      "\u001B[?25hInstalling collected packages: mathparse, blis, thinc, spacy, chatterbot\r\n",
      "  Attempting uninstall: blis\r\n",
      "    Found existing installation: blis 0.7.11\r\n",
      "    Uninstalling blis-0.7.11:\r\n",
      "      Successfully uninstalled blis-0.7.11\r\n",
      "  Attempting uninstall: thinc\r\n",
      "    Found existing installation: thinc 8.2.5\r\n",
      "    Uninstalling thinc-8.2.5:\r\n",
      "      Successfully uninstalled thinc-8.2.5\r\n",
      "  Attempting uninstall: spacy\r\n",
      "    Found existing installation: spacy 3.7.5\r\n",
      "    Uninstalling spacy-3.7.5:\r\n",
      "      Successfully uninstalled spacy-3.7.5\r\n",
      "\u001B[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\r\n",
      "fr-core-news-md 3.7.0 requires spacy<3.8.0,>=3.7.0, but you have spacy 3.8.4 which is incompatible.\r\n",
      "de-core-news-lg 3.7.0 requires spacy<3.8.0,>=3.7.0, but you have spacy 3.8.4 which is incompatible.\r\n",
      "en-core-web-lg 3.7.1 requires spacy<3.8.0,>=3.7.2, but you have spacy 3.8.4 which is incompatible.\u001B[0m\u001B[31m\r\n",
      "\u001B[0mSuccessfully installed blis-1.2.0 chatterbot-1.2.3 mathparse-0.1.2 spacy-3.8.4 thinc-8.3.4\r\n",
      "Looking in indexes: https://pypi.org/simple, https://aishwarya.mundalik:****@artifactory.softgarden.de/artifactory/api/pypi/python-local/simple\r\n",
      "\u001B[33mWARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10dd0cbd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /artifactory/api/pypi/python-local/simple/chatterbot-corpus/\u001B[0m\u001B[33m\r\n",
      "\u001B[0m\u001B[33mWARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10dd0c250>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /artifactory/api/pypi/python-local/simple/chatterbot-corpus/\u001B[0m\u001B[33m\r\n",
      "\u001B[0m\u001B[33mWARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10dd0db50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /artifactory/api/pypi/python-local/simple/chatterbot-corpus/\u001B[0m\u001B[33m\r\n",
      "\u001B[0m\u001B[33mWARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10dd0e390>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /artifactory/api/pypi/python-local/simple/chatterbot-corpus/\u001B[0m\u001B[33m\r\n",
      "\u001B[0m\u001B[33mWARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x10dd0ebd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')': /artifactory/api/pypi/python-local/simple/chatterbot-corpus/\u001B[0m\u001B[33m\r\n",
      "\u001B[0mCollecting chatterbot_corpus\r\n",
      "  Downloading chatterbot_corpus-1.2.2-py2.py3-none-any.whl.metadata (1.1 kB)\r\n",
      "Downloading chatterbot_corpus-1.2.2-py2.py3-none-any.whl (240 kB)\r\n",
      "Installing collected packages: chatterbot_corpus\r\n",
      "Successfully installed chatterbot_corpus-1.2.2\r\n"
     ]
    }
   ],
   "source": [
    "!pip install textblob nltk\n",
    "!pip install chatterbot\n",
    "!pip install chatterbot_corpus\n",
    "!python -m spacy download en_core_web_sm"
   ],
   "metadata": {
    "collapsed": false,
    "ExecuteTime": {
     "end_time": "2025-03-24T21:10:57.260695Z",
     "start_time": "2025-03-24T21:09:54.275631Z"
    }
   },
   "id": "574e0ef76916d85c"
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[nltk_data] Downloading package punkt to\n",
      "[nltk_data]     /Users/aishwaryamundalik/nltk_data...\n",
      "[nltk_data]   Package punkt is already up-to-date!\n"
     ]
    },
    {
     "data": {
      "text/plain": "True"
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#imports \n",
    "import nltk\n",
    "import random\n",
    "nltk.download('punkt')"
   ],
   "metadata": {
    "collapsed": false,
    "ExecuteTime": {
     "end_time": "2025-03-24T21:25:16.153993Z",
     "start_time": "2025-03-24T21:25:16.149041Z"
    }
   },
   "id": "dab5301a15f04359"
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "outputs": [],
   "source": [
    "# greetings and goodbyes \n",
    "greetings = ['hi', 'hello', 'hey', 'howdy', 'greetings', 'what\\'s up']\n",
    "goodbyes = [\n",
    "    'bye', 'goodbye', 'see you', 'take care', 'later',         # English\n",
    "    'adios', 'hasta luego', 'chau', 'nos vemos', 'hasta la vista',  # Spanish\n",
    "    'au revoir', 'salut', 'à bientôt', 'bye bye',               # French\n",
    "    'tschüss', 'auf Wiedersehen', 'bis bald',                   # German\n",
    "    'arrivederci', 'ciao', 'addio', 'a presto',                 # Italian\n",
    "    'до свидания', 'пока', 'прощай',                             # Russian\n",
    "    'さようなら', 'じゃね', 'お疲れ様',                             # Japanese\n",
    "    '안녕', '잘 가', '다음에 봐요'                                 # Korean\n",
    "]\n"
   ],
   "metadata": {
    "collapsed": false,
    "ExecuteTime": {
     "end_time": "2025-03-24T21:27:58.260992Z",
     "start_time": "2025-03-24T21:27:58.259715Z"
    }
   },
   "id": "4389b254e7f1f21c"
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "outputs": [],
   "source": [
    "#Trump'S  famous dialogs\n",
    "def trump_responses(user_input):\n",
    "    user_input = user_input.lower()\n",
    "\n",
    "    # Positive\n",
    "    positive_responses = [\n",
    "        \"Tremendous! You’re really doing great, believe me.\",\n",
    "        \"I’m telling you, nobody does it better than me. Nobody!\",\n",
    "        \"This is amazing, the best conversation, we’ve had so far. Everybody’s talking about it!\",\n",
    "        \"I love it, you're incredible. Just incredible.\",\n",
    "        \"People are saying this is the best chat ever, I’m the best at this, believe me.\"\n",
    "    ]\n",
    "\n",
    "    # Default\n",
    "    default_responses = [\n",
    "        \"You know, I have the best responses. Nobody has better responses, it's incredible.\",\n",
    "        \"I’m just the best chatbot, no question about it. Believe me.\",\n",
    "        \"You won’t believe it, but I’ve heard this is the greatest chatbot of all time, incredible.\",\n",
    "        \"I’ve spoken with the best people, and let me tell you, this conversation is huge!\"\n",
    "    ]\n",
    "\n",
    "    # Famous Trump\n",
    "    trump_quotes = [\n",
    "        \"Make America Great Again!\",\n",
    "        \"You’re gonna get tired of winning. Believe me.\",\n",
    "        \"I will be the greatest jobs president that God ever created. I tell you that.\",\n",
    "        \"Nobody builds walls better than me, believe me.\",\n",
    "        \"I have the best words. I have the best words, believe me.\",\n",
    "        \"We will have so much winning if I get elected that you may get bored with winning.\",\n",
    "        \"It’s going to be huge. Huge, believe me!\"\n",
    "    ]\n",
    "\n",
    "    # If user says hi\n",
    "    if any(greet in user_input for greet in greetings):\n",
    "        return random.choice([\n",
    "            \"Hi there! I have the best greetings, just tremendous!\",\n",
    "            \"Hello! Nobody greets like me, trust me.\",\n",
    "            \"Hey! I’m the best at saying hi. Incredible, right?\"\n",
    "        ])\n",
    "\n",
    "    # If user says bye\n",
    "    elif any(farewell in user_input for farewell in goodbyes):\n",
    "        return random.choice([\n",
    "            \"Goodbye, folks! We'll talk again. It’s been tremendous!\",\n",
    "            \"See you later, we’ll do this again. Believe me, it’s huge!\",\n",
    "            \"Take care, it’s been fantastic. Everybody’s talking about it!\"\n",
    "        ])\n",
    "\n",
    "    # If user seems happy or positive\n",
    "    elif any(word in user_input for word in [\"happy\", \"good\", \"excited\", \"awesome\", \"great\", \"amazing\"]):\n",
    "        return random.choice(positive_responses)\n",
    "\n",
    "    # If the user asks for something motivational or needs encouragement\n",
    "    elif 'motivation' in user_input or 'advice' in user_input:\n",
    "        return random.choice([\n",
    "            \"You’re going to do great things, believe me! Just keep pushing!\",\n",
    "            \"Nobody does it better than you, I’m telling you. You got this!\",\n",
    "            \"Trust me, I know success. You will be the best, just like me!\"\n",
    "        ])\n",
    "\n",
    "    # If user mentions something about winning\n",
    "    elif 'win' in user_input or 'success' in user_input:\n",
    "        return random.choice([\n",
    "            \"You're going to win so much you won’t know what to do with yourself. It’s going to be incredible.\",\n",
    "            \"Nobody knows how to win better than I do. Trust me.\",\n",
    "            \"Success is a choice, and you’re on the right path!\"\n",
    "        ])\n",
    "\n",
    "    # Default response when no other conditions match (Trump-style)\n",
    "    else:\n",
    "        return random.choice(default_responses)\n",
    "\n",
    "    # Add a random Trump quote occasionally\n",
    "    if random.random() < 0.1:  # 10% chance to return a Trump quote\n",
    "        return random.choice(trump_quotes)\n",
    "\n"
   ],
   "metadata": {
    "collapsed": false,
    "ExecuteTime": {
     "end_time": "2025-03-24T21:27:58.509959Z",
     "start_time": "2025-03-24T21:27:58.502767Z"
    }
   },
   "id": "d775e2e2eac8ccd8"
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Hello, I am TrumpBot! Let’s chat! Type 'exit' to stop. It’s going to be huge.\n",
      "TrumpBot: Success is a choice, and you’re on the right path!\n",
      "TrumpBot: You're going to win so much you won’t know what to do with yourself. It’s going to be incredible.\n",
      "TrumpBot: You won’t believe it, but I’ve heard this is the greatest chatbot of all time, incredible.\n",
      "TrumpBot: You know, I have the best responses. Nobody has better responses, it's incredible.\n",
      "TrumpBot: I’m just the best chatbot, no question about it. Believe me.\n",
      "TrumpBot: Goodbye, folks! It's been incredible! Come back soon!\n"
     ]
    }
   ],
   "source": [
    "# TrumpBot Conversation Loop\n",
    "print(\"Hello, I am TrumpBot! Let’s chat! Type 'exit' to stop. It’s going to be huge.\")\n",
    "\n",
    "while True:\n",
    "    user_input = input(\"You: \")\n",
    "\n",
    "    # 'exit' commands\n",
    "    if any(farewell in user_input.lower() for farewell in goodbyes):\n",
    "        print(\"TrumpBot: Goodbye, folks! It's been incredible! Come back soon!\")\n",
    "        break\n",
    "\n",
    "    #response from the trump_responses function\n",
    "    response = trump_responses(user_input)\n",
    "\n",
    "    #chatbot's response\n",
    "    print(\"TrumpBot: \" + response)"
   ],
   "metadata": {
    "collapsed": false,
    "ExecuteTime": {
     "end_time": "2025-03-24T21:28:32.144175Z",
     "start_time": "2025-03-24T21:27:58.676626Z"
    }
   },
   "id": "11d152a3cc142b0"
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "outputs": [],
   "source": [],
   "metadata": {
    "collapsed": false
   },
   "id": "b2edf6e78e31d8b9"
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
